name: "helm-github-branch-release"
inputs:
  token:
    required: false
  version:
    required: false
    default: .
  author-email:
    required: true
  author-name:
    required: true
  commit-message:
    required: false
    default: release and update index
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      #with:
        #token: ${{ inputs.token }}
    - uses: azure/setup-helm@v3
    - shell: bash
      run: |
        helm package .
        helm repo index ${{ inputs.version }}
        git config --global user.email "${{ inputs.author-email }}"
        git config --global user.name "${{ inputs.author-name }}"
        git add .
        git status
        git commit -m "${{ inputs.commit-message }}"
        git push
    # git config --global user.email "yourbot@yourorg.com"
    # git config --global user.name "YourOrg Bot"
