name: "Docker base image CI"
inputs:
  registry:
    required: false
    default: ghcr.io
  username:
    required: true
  password:
    required: true
  tag:
    required: true
  context:
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v2
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - uses: docker/build-push-action@v3
      with:
        context: ${{ inputs.context }}
        push: true
        tags: ${{ inputs.registry }}/${{ inputs.tag }}
